// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Uint64Array uint64 array
//
// swagger:model uint64Array
type Uint64Array []uint64

// Validate validates this uint64 array
func (m Uint64Array) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this uint64 array based on context it is used
func (m Uint64Array) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
