// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AutotuneConfig autotune config
//
// swagger:model autotuneConfig
type AutotuneConfig struct {

	// percent variation
	PercentVariation *bool `json:"percentVariation,omitempty"`

	// range
	Range *bool `json:"range,omitempty"`
}

// Validate validates this autotune config
func (m *AutotuneConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this autotune config based on context it is used
func (m *AutotuneConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AutotuneConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AutotuneConfig) UnmarshalBinary(b []byte) error {
	var res AutotuneConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
