// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FeatureConfigResponse feature config response
//
// swagger:model featureConfigResponse
type FeatureConfigResponse struct {
	FeatureConfig

	// Whether `minVal` and `maxVal` have been set for this feature (through either configuration or autotuning). `minVal` and `maxVal` are undefined when this field is false.
	MinMaxDefined bool `json:"minMaxDefined,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *FeatureConfigResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 FeatureConfig
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.FeatureConfig = aO0

	// AO1
	var dataAO1 struct {
		MinMaxDefined bool `json:"minMaxDefined,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.MinMaxDefined = dataAO1.MinMaxDefined

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m FeatureConfigResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.FeatureConfig)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		MinMaxDefined bool `json:"minMaxDefined,omitempty"`
	}

	dataAO1.MinMaxDefined = m.MinMaxDefined

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this feature config response
func (m *FeatureConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with FeatureConfig
	if err := m.FeatureConfig.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this feature config response based on the context it is used
func (m *FeatureConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with FeatureConfig
	if err := m.FeatureConfig.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *FeatureConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FeatureConfigResponse) UnmarshalBinary(b []byte) error {
	var res FeatureConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
