// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetVersionResponse get version response
//
// swagger:model getVersionResponse
type GetVersionResponse struct {

	// SHA-1 of `amber-store`.
	AmberStore string `json:"amber-store,omitempty"`

	// API version.
	APIVersion string `json:"api-version,omitempty"`

	// SHA-1 of `builder`.
	Builder string `json:"builder,omitempty"`

	// SHA-1 of `expert-api`.
	ExpertAPI string `json:"expert-api,omitempty"`

	// SHA-1 of `expert-common`.
	ExpertCommon string `json:"expert-common,omitempty"`

	// SHA-1 of `mongolia`.
	Mongolia string `json:"mongolia,omitempty"`

	// SHA-1 of `nano-secure`.
	NanoSecure string `json:"nano-secure,omitempty"`

	// Software release of server.
	Release string `json:"release,omitempty"`

	// SHA-1 of Swagger UI.
	SwaggerUI string `json:"swagger-ui,omitempty"`
}

// Validate validates this get version response
func (m *GetVersionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get version response based on context it is used
func (m *GetVersionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetVersionResponse) UnmarshalBinary(b []byte) error {
	var res GetVersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
