// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PercentVariation Granularity of the underlying cluster model used for anomaly detection. This is a number between 0.01 and 0.20 which is the distance threshold used to determine whether a pattern should be assigned to an existing cluster or create a new cluster of its own. All things held equal, a small `percentVariation` will segment a dataset into many clusters while a larger `percentVariation` will segment the dataset into fewer clusters.
//
// `percentVariation` can be left unset if it is not known at configuration time. In that case, data collected during the `Buffering` stage will be used to infer an optimal `percentVariation` during the `Autotuning` stage and it will be set to the autotuned value at the start of `Learning`.
//
// swagger:model percentVariation
type PercentVariation float32

// Validate validates this percent variation
func (m PercentVariation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this percent variation based on context it is used
func (m PercentVariation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
