// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostLearningRequest post learning request
//
// swagger:model postLearningRequest
type PostLearningRequest struct {

	// training
	Training *TrainingConfig `json:"training,omitempty"`
}

// Validate validates this post learning request
func (m *PostLearningRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTraining(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostLearningRequest) validateTraining(formats strfmt.Registry) error {
	if swag.IsZero(m.Training) { // not required
		return nil
	}

	if m.Training != nil {
		if err := m.Training.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("training")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("training")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post learning request based on the context it is used
func (m *PostLearningRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTraining(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostLearningRequest) contextValidateTraining(ctx context.Context, formats strfmt.Registry) error {

	if m.Training != nil {
		if err := m.Training.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("training")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("training")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostLearningRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostLearningRequest) UnmarshalBinary(b []byte) error {
	var res PostLearningRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
