// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostPretrainResponse post pretrain response
//
// swagger:model postPretrainResponse
type PostPretrainResponse struct {
	PretrainStatus

	// Chunk specifier for chunked uploads.
	Chunkspec string `json:"chunkspec,omitempty"`

	// Transaction id for chunked uploads.
	TxnID string `json:"txnId,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostPretrainResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 PretrainStatus
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.PretrainStatus = aO0

	// AO1
	var dataAO1 struct {
		Chunkspec string `json:"chunkspec,omitempty"`

		TxnID string `json:"txnId,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Chunkspec = dataAO1.Chunkspec

	m.TxnID = dataAO1.TxnID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostPretrainResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.PretrainStatus)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Chunkspec string `json:"chunkspec,omitempty"`

		TxnID string `json:"txnId,omitempty"`
	}

	dataAO1.Chunkspec = m.Chunkspec

	dataAO1.TxnID = m.TxnID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post pretrain response
func (m *PostPretrainResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with PretrainStatus
	if err := m.PretrainStatus.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this post pretrain response based on the context it is used
func (m *PostPretrainResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with PretrainStatus
	if err := m.PretrainStatus.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostPretrainResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostPretrainResponse) UnmarshalBinary(b []byte) error {
	var res PostPretrainResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
