// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostModelCopyRequest post model copy request
//
// swagger:model postModelCopyRequest
type PostModelCopyRequest struct {

	// Label for the new model. Allowed characters: `+.:_-` and any alphanumeric.
	Label *string `json:"label,omitempty"`
}

// Validate validates this post model copy request
func (m *PostModelCopyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post model copy request based on context it is used
func (m *PostModelCopyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostModelCopyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostModelCopyRequest) UnmarshalBinary(b []byte) error {
	var res PostModelCopyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
