// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDataRequest post data request
//
// swagger:model postDataRequest
type PostDataRequest struct {

	// Data as a flat list of comma-separated values. The number of values sent must be a multiple of the number of features in the configuration.
	// Required: true
	Data *string `json:"data"`

	// If false, saved model image will not be updated on this request. Applies only to on-premises deployments.
	SaveImage *bool `json:"saveImage,omitempty"`
}

// Validate validates this post data request
func (m *PostDataRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDataRequest) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post data request based on context it is used
func (m *PostDataRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostDataRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDataRequest) UnmarshalBinary(b []byte) error {
	var res PostDataRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
