// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostPretrainResponse post pretrain response
//
// swagger:model postPretrainResponse
type PostPretrainResponse struct {

	// amber chunk
	AmberChunk string `json:"amberChunk,omitempty"`

	// amber transaction
	AmberTransaction string `json:"amberTransaction,omitempty"`

	// latest pretrain message
	Message string `json:"message,omitempty"`

	// state of pretraining, one of: Chunking, Pretraining, Pretrained, Error
	// Required: true
	State *string `json:"state"`
}

// Validate validates this post pretrain response
func (m *PostPretrainResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostPretrainResponse) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post pretrain response based on context it is used
func (m *PostPretrainResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostPretrainResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostPretrainResponse) UnmarshalBinary(b []byte) error {
	var res PostPretrainResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
