// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAuth2Response post auth2 response
//
// swagger:model postAuth2Response
type PostAuth2Response struct {

	// Amount of time before token expires
	// Required: true
	ExpiresIn *string `json:"expiresIn"`

	// Identifier token to be used as Bearer token
	// Required: true
	IDToken *string `json:"idToken"`

	// Refresh token identifier
	// Required: true
	RefreshToken *string `json:"refreshToken"`

	// Type of authentication token
	// Required: true
	TokenType *string `json:"tokenType"`
}

// Validate validates this post auth2 response
func (m *PostAuth2Response) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresIn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefreshToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostAuth2Response) validateExpiresIn(formats strfmt.Registry) error {

	if err := validate.Required("expiresIn", "body", m.ExpiresIn); err != nil {
		return err
	}

	return nil
}

func (m *PostAuth2Response) validateIDToken(formats strfmt.Registry) error {

	if err := validate.Required("idToken", "body", m.IDToken); err != nil {
		return err
	}

	return nil
}

func (m *PostAuth2Response) validateRefreshToken(formats strfmt.Registry) error {

	if err := validate.Required("refreshToken", "body", m.RefreshToken); err != nil {
		return err
	}

	return nil
}

func (m *PostAuth2Response) validateTokenType(formats strfmt.Registry) error {

	if err := validate.Required("tokenType", "body", m.TokenType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post auth2 response based on context it is used
func (m *PostAuth2Response) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostAuth2Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAuth2Response) UnmarshalBinary(b []byte) error {
	var res PostAuth2Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
