// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutSensorResponse put sensor response
//
// swagger:model putSensorResponse
type PutSensorResponse struct {

	// Additional label to be assigned for sensor
	// Required: true
	Label *string `json:"label"`

	// Unique identifier for sensor
	// Required: true
	SensorID *string `json:"sensorId"`
}

// Validate validates this put sensor response
func (m *PutSensorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSensorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PutSensorResponse) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

func (m *PutSensorResponse) validateSensorID(formats strfmt.Registry) error {

	if err := validate.Required("sensorId", "body", m.SensorID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this put sensor response based on context it is used
func (m *PutSensorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PutSensorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutSensorResponse) UnmarshalBinary(b []byte) error {
	var res PutSensorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
