// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Uint32Array uint32 array
//
// swagger:model uint32Array
type Uint32Array []uint32

// Validate validates this uint32 array
func (m Uint32Array) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this uint32 array based on context it is used
func (m Uint32Array) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
