// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// DeleteModelReader is a Reader for the DeleteModel structure.
type DeleteModelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteModelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteModelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteModelUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteModelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteModelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteModelOK creates a DeleteModelOK with default headers values
func NewDeleteModelOK() *DeleteModelOK {
	return &DeleteModelOK{}
}

/*
	DeleteModelOK describes a response with status code 200, with default header values.

OK
*/
type DeleteModelOK struct {
	Payload *models.DeleteModelResponse
}

func (o *DeleteModelOK) Error() string {
	return fmt.Sprintf("[DELETE /models/{modelId}][%d] deleteModelOK  %+v", 200, o.Payload)
}
func (o *DeleteModelOK) GetPayload() *models.DeleteModelResponse {
	return o.Payload
}

func (o *DeleteModelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteModelResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteModelUnauthorized creates a DeleteModelUnauthorized with default headers values
func NewDeleteModelUnauthorized() *DeleteModelUnauthorized {
	return &DeleteModelUnauthorized{}
}

/*
	DeleteModelUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteModelUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteModelUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /models/{modelId}][%d] deleteModelUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteModelUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteModelUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteModelNotFound creates a DeleteModelNotFound with default headers values
func NewDeleteModelNotFound() *DeleteModelNotFound {
	return &DeleteModelNotFound{}
}

/*
	DeleteModelNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type DeleteModelNotFound struct {
	Payload *models.Error
}

func (o *DeleteModelNotFound) Error() string {
	return fmt.Sprintf("[DELETE /models/{modelId}][%d] deleteModelNotFound  %+v", 404, o.Payload)
}
func (o *DeleteModelNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteModelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteModelInternalServerError creates a DeleteModelInternalServerError with default headers values
func NewDeleteModelInternalServerError() *DeleteModelInternalServerError {
	return &DeleteModelInternalServerError{}
}

/*
	DeleteModelInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteModelInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteModelInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /models/{modelId}][%d] deleteModelInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteModelInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteModelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
