// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// GetModelReader is a Reader for the GetModel structure.
type GetModelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetModelUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetModelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetModelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetModelOK creates a GetModelOK with default headers values
func NewGetModelOK() *GetModelOK {
	return &GetModelOK{}
}

/*
	GetModelOK describes a response with status code 200, with default header values.

OK
*/
type GetModelOK struct {
	Payload *models.PostModelResponse
}

func (o *GetModelOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelOK  %+v", 200, o.Payload)
}
func (o *GetModelOK) GetPayload() *models.PostModelResponse {
	return o.Payload
}

func (o *GetModelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostModelResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelUnauthorized creates a GetModelUnauthorized with default headers values
func NewGetModelUnauthorized() *GetModelUnauthorized {
	return &GetModelUnauthorized{}
}

/*
	GetModelUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetModelUnauthorized struct {
	Payload *models.Error
}

func (o *GetModelUnauthorized) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelUnauthorized  %+v", 401, o.Payload)
}
func (o *GetModelUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelNotFound creates a GetModelNotFound with default headers values
func NewGetModelNotFound() *GetModelNotFound {
	return &GetModelNotFound{}
}

/*
	GetModelNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetModelNotFound struct {
	Payload *models.Error
}

func (o *GetModelNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelNotFound  %+v", 404, o.Payload)
}
func (o *GetModelNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelInternalServerError creates a GetModelInternalServerError with default headers values
func NewGetModelInternalServerError() *GetModelInternalServerError {
	return &GetModelInternalServerError{}
}

/*
	GetModelInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetModelInternalServerError struct {
	Payload *models.Error
}

func (o *GetModelInternalServerError) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelInternalServerError  %+v", 500, o.Payload)
}
func (o *GetModelInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
