// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// GetModelDataSetRunReader is a Reader for the GetModelDataSetRun structure.
type GetModelDataSetRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelDataSetRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelDataSetRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewGetModelDataSetRunAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetModelDataSetRunBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetModelDataSetRunUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetModelDataSetRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetModelDataSetRunInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetModelDataSetRunOK creates a GetModelDataSetRunOK with default headers values
func NewGetModelDataSetRunOK() *GetModelDataSetRunOK {
	return &GetModelDataSetRunOK{}
}

/*
	GetModelDataSetRunOK describes a response with status code 200, with default header values.

OK
*/
type GetModelDataSetRunOK struct {
	Payload *models.GetModelDataSetRunResponse
}

func (o *GetModelDataSetRunOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunOK  %+v", 200, o.Payload)
}
func (o *GetModelDataSetRunOK) GetPayload() *models.GetModelDataSetRunResponse {
	return o.Payload
}

func (o *GetModelDataSetRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetModelDataSetRunResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelDataSetRunAccepted creates a GetModelDataSetRunAccepted with default headers values
func NewGetModelDataSetRunAccepted() *GetModelDataSetRunAccepted {
	return &GetModelDataSetRunAccepted{}
}

/*
	GetModelDataSetRunAccepted describes a response with status code 202, with default header values.

Operation was accepted
*/
type GetModelDataSetRunAccepted struct {
	Payload *models.GetModelDataSetRunResponse
}

func (o *GetModelDataSetRunAccepted) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunAccepted  %+v", 202, o.Payload)
}
func (o *GetModelDataSetRunAccepted) GetPayload() *models.GetModelDataSetRunResponse {
	return o.Payload
}

func (o *GetModelDataSetRunAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetModelDataSetRunResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelDataSetRunBadRequest creates a GetModelDataSetRunBadRequest with default headers values
func NewGetModelDataSetRunBadRequest() *GetModelDataSetRunBadRequest {
	return &GetModelDataSetRunBadRequest{}
}

/*
	GetModelDataSetRunBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetModelDataSetRunBadRequest struct {
	Payload *models.Error
}

func (o *GetModelDataSetRunBadRequest) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunBadRequest  %+v", 400, o.Payload)
}
func (o *GetModelDataSetRunBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelDataSetRunBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelDataSetRunUnauthorized creates a GetModelDataSetRunUnauthorized with default headers values
func NewGetModelDataSetRunUnauthorized() *GetModelDataSetRunUnauthorized {
	return &GetModelDataSetRunUnauthorized{}
}

/*
	GetModelDataSetRunUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetModelDataSetRunUnauthorized struct {
	Payload *models.Error
}

func (o *GetModelDataSetRunUnauthorized) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunUnauthorized  %+v", 401, o.Payload)
}
func (o *GetModelDataSetRunUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelDataSetRunUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelDataSetRunNotFound creates a GetModelDataSetRunNotFound with default headers values
func NewGetModelDataSetRunNotFound() *GetModelDataSetRunNotFound {
	return &GetModelDataSetRunNotFound{}
}

/*
	GetModelDataSetRunNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetModelDataSetRunNotFound struct {
	Payload *models.Error
}

func (o *GetModelDataSetRunNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunNotFound  %+v", 404, o.Payload)
}
func (o *GetModelDataSetRunNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelDataSetRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelDataSetRunInternalServerError creates a GetModelDataSetRunInternalServerError with default headers values
func NewGetModelDataSetRunInternalServerError() *GetModelDataSetRunInternalServerError {
	return &GetModelDataSetRunInternalServerError{}
}

/*
	GetModelDataSetRunInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetModelDataSetRunInternalServerError struct {
	Payload *models.Error
}

func (o *GetModelDataSetRunInternalServerError) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/dataset/run][%d] getModelDataSetRunInternalServerError  %+v", 500, o.Payload)
}
func (o *GetModelDataSetRunInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelDataSetRunInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
