// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// GetModelNanoStatusReader is a Reader for the GetModelNanoStatus structure.
type GetModelNanoStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelNanoStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelNanoStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetModelNanoStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetModelNanoStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetModelNanoStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetModelNanoStatusOK creates a GetModelNanoStatusOK with default headers values
func NewGetModelNanoStatusOK() *GetModelNanoStatusOK {
	return &GetModelNanoStatusOK{}
}

/*
	GetModelNanoStatusOK describes a response with status code 200, with default header values.

OK
*/
type GetModelNanoStatusOK struct {
	Payload *models.GetNanoStatusResponse
}

func (o *GetModelNanoStatusOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status/nano][%d] getModelNanoStatusOK  %+v", 200, o.Payload)
}
func (o *GetModelNanoStatusOK) GetPayload() *models.GetNanoStatusResponse {
	return o.Payload
}

func (o *GetModelNanoStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNanoStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelNanoStatusUnauthorized creates a GetModelNanoStatusUnauthorized with default headers values
func NewGetModelNanoStatusUnauthorized() *GetModelNanoStatusUnauthorized {
	return &GetModelNanoStatusUnauthorized{}
}

/*
	GetModelNanoStatusUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetModelNanoStatusUnauthorized struct {
	Payload *models.Error
}

func (o *GetModelNanoStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status/nano][%d] getModelNanoStatusUnauthorized  %+v", 401, o.Payload)
}
func (o *GetModelNanoStatusUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelNanoStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelNanoStatusNotFound creates a GetModelNanoStatusNotFound with default headers values
func NewGetModelNanoStatusNotFound() *GetModelNanoStatusNotFound {
	return &GetModelNanoStatusNotFound{}
}

/*
	GetModelNanoStatusNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetModelNanoStatusNotFound struct {
	Payload *models.Error
}

func (o *GetModelNanoStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status/nano][%d] getModelNanoStatusNotFound  %+v", 404, o.Payload)
}
func (o *GetModelNanoStatusNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelNanoStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelNanoStatusInternalServerError creates a GetModelNanoStatusInternalServerError with default headers values
func NewGetModelNanoStatusInternalServerError() *GetModelNanoStatusInternalServerError {
	return &GetModelNanoStatusInternalServerError{}
}

/*
	GetModelNanoStatusInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetModelNanoStatusInternalServerError struct {
	Payload *models.Error
}

func (o *GetModelNanoStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status/nano][%d] getModelNanoStatusInternalServerError  %+v", 500, o.Payload)
}
func (o *GetModelNanoStatusInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelNanoStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
