// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// GetModelPretrainReader is a Reader for the GetModelPretrain structure.
type GetModelPretrainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelPretrainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelPretrainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewGetModelPretrainAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetModelPretrainUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetModelPretrainNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetModelPretrainInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetModelPretrainOK creates a GetModelPretrainOK with default headers values
func NewGetModelPretrainOK() *GetModelPretrainOK {
	return &GetModelPretrainOK{}
}

/*
	GetModelPretrainOK describes a response with status code 200, with default header values.

Model is not pretraining
*/
type GetModelPretrainOK struct {
	Payload *models.GetPretrainResponse
}

func (o *GetModelPretrainOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/pretrain][%d] getModelPretrainOK  %+v", 200, o.Payload)
}
func (o *GetModelPretrainOK) GetPayload() *models.GetPretrainResponse {
	return o.Payload
}

func (o *GetModelPretrainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPretrainResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelPretrainAccepted creates a GetModelPretrainAccepted with default headers values
func NewGetModelPretrainAccepted() *GetModelPretrainAccepted {
	return &GetModelPretrainAccepted{}
}

/*
	GetModelPretrainAccepted describes a response with status code 202, with default header values.

Model is currently pretraining
*/
type GetModelPretrainAccepted struct {
	Payload *models.GetPretrainResponse
}

func (o *GetModelPretrainAccepted) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/pretrain][%d] getModelPretrainAccepted  %+v", 202, o.Payload)
}
func (o *GetModelPretrainAccepted) GetPayload() *models.GetPretrainResponse {
	return o.Payload
}

func (o *GetModelPretrainAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetPretrainResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelPretrainUnauthorized creates a GetModelPretrainUnauthorized with default headers values
func NewGetModelPretrainUnauthorized() *GetModelPretrainUnauthorized {
	return &GetModelPretrainUnauthorized{}
}

/*
	GetModelPretrainUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetModelPretrainUnauthorized struct {
	Payload *models.Error
}

func (o *GetModelPretrainUnauthorized) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/pretrain][%d] getModelPretrainUnauthorized  %+v", 401, o.Payload)
}
func (o *GetModelPretrainUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelPretrainUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelPretrainNotFound creates a GetModelPretrainNotFound with default headers values
func NewGetModelPretrainNotFound() *GetModelPretrainNotFound {
	return &GetModelPretrainNotFound{}
}

/*
	GetModelPretrainNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetModelPretrainNotFound struct {
	Payload *models.Error
}

func (o *GetModelPretrainNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/pretrain][%d] getModelPretrainNotFound  %+v", 404, o.Payload)
}
func (o *GetModelPretrainNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelPretrainNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelPretrainInternalServerError creates a GetModelPretrainInternalServerError with default headers values
func NewGetModelPretrainInternalServerError() *GetModelPretrainInternalServerError {
	return &GetModelPretrainInternalServerError{}
}

/*
	GetModelPretrainInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetModelPretrainInternalServerError struct {
	Payload *models.Error
}

func (o *GetModelPretrainInternalServerError) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/pretrain][%d] getModelPretrainInternalServerError  %+v", 500, o.Payload)
}
func (o *GetModelPretrainInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelPretrainInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
