// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetModelSummaryParams creates a new GetModelSummaryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModelSummaryParams() *GetModelSummaryParams {
	return &GetModelSummaryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModelSummaryParamsWithTimeout creates a new GetModelSummaryParams object
// with the ability to set a timeout on a request.
func NewGetModelSummaryParamsWithTimeout(timeout time.Duration) *GetModelSummaryParams {
	return &GetModelSummaryParams{
		timeout: timeout,
	}
}

// NewGetModelSummaryParamsWithContext creates a new GetModelSummaryParams object
// with the ability to set a context for a request.
func NewGetModelSummaryParamsWithContext(ctx context.Context) *GetModelSummaryParams {
	return &GetModelSummaryParams{
		Context: ctx,
	}
}

// NewGetModelSummaryParamsWithHTTPClient creates a new GetModelSummaryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModelSummaryParamsWithHTTPClient(client *http.Client) *GetModelSummaryParams {
	return &GetModelSummaryParams{
		HTTPClient: client,
	}
}

/*
GetModelSummaryParams contains all the parameters to send to the API endpoint

	for the get model summary operation.

	Typically these are written to a http.Request.
*/
type GetModelSummaryParams struct {

	// ModelID.
	ModelID string

	/* TrainingSamples.

	   Whether to return training samples
	*/
	TrainingSamples *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get model summary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelSummaryParams) WithDefaults() *GetModelSummaryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get model summary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelSummaryParams) SetDefaults() {
	var (
		trainingSamplesDefault = bool(false)
	)

	val := GetModelSummaryParams{
		TrainingSamples: &trainingSamplesDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get model summary params
func (o *GetModelSummaryParams) WithTimeout(timeout time.Duration) *GetModelSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get model summary params
func (o *GetModelSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get model summary params
func (o *GetModelSummaryParams) WithContext(ctx context.Context) *GetModelSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get model summary params
func (o *GetModelSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get model summary params
func (o *GetModelSummaryParams) WithHTTPClient(client *http.Client) *GetModelSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get model summary params
func (o *GetModelSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModelID adds the modelID to the get model summary params
func (o *GetModelSummaryParams) WithModelID(modelID string) *GetModelSummaryParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the get model summary params
func (o *GetModelSummaryParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WithTrainingSamples adds the trainingSamples to the get model summary params
func (o *GetModelSummaryParams) WithTrainingSamples(trainingSamples *bool) *GetModelSummaryParams {
	o.SetTrainingSamples(trainingSamples)
	return o
}

// SetTrainingSamples adds the trainingSamples to the get model summary params
func (o *GetModelSummaryParams) SetTrainingSamples(trainingSamples *bool) {
	o.TrainingSamples = trainingSamples
}

// WriteToRequest writes these params to a swagger request
func (o *GetModelSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param modelId
	if err := r.SetPathParam("modelId", o.ModelID); err != nil {
		return err
	}

	if o.TrainingSamples != nil {

		// query param trainingSamples
		var qrTrainingSamples bool

		if o.TrainingSamples != nil {
			qrTrainingSamples = *o.TrainingSamples
		}
		qTrainingSamples := swag.FormatBool(qrTrainingSamples)
		if qTrainingSamples != "" {

			if err := r.SetQueryParam("trainingSamples", qTrainingSamples); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
