// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetModelStatusParams creates a new GetModelStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModelStatusParams() *GetModelStatusParams {
	return &GetModelStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModelStatusParamsWithTimeout creates a new GetModelStatusParams object
// with the ability to set a timeout on a request.
func NewGetModelStatusParamsWithTimeout(timeout time.Duration) *GetModelStatusParams {
	return &GetModelStatusParams{
		timeout: timeout,
	}
}

// NewGetModelStatusParamsWithContext creates a new GetModelStatusParams object
// with the ability to set a context for a request.
func NewGetModelStatusParamsWithContext(ctx context.Context) *GetModelStatusParams {
	return &GetModelStatusParams{
		Context: ctx,
	}
}

// NewGetModelStatusParamsWithHTTPClient creates a new GetModelStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModelStatusParamsWithHTTPClient(client *http.Client) *GetModelStatusParams {
	return &GetModelStatusParams{
		HTTPClient: client,
	}
}

/*
GetModelStatusParams contains all the parameters to send to the API endpoint

	for the get model status operation.

	Typically these are written to a http.Request.
*/
type GetModelStatusParams struct {

	// ModelID.
	ModelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get model status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelStatusParams) WithDefaults() *GetModelStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get model status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get model status params
func (o *GetModelStatusParams) WithTimeout(timeout time.Duration) *GetModelStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get model status params
func (o *GetModelStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get model status params
func (o *GetModelStatusParams) WithContext(ctx context.Context) *GetModelStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get model status params
func (o *GetModelStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get model status params
func (o *GetModelStatusParams) WithHTTPClient(client *http.Client) *GetModelStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get model status params
func (o *GetModelStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModelID adds the modelID to the get model status params
func (o *GetModelStatusParams) WithModelID(modelID string) *GetModelStatusParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the get model status params
func (o *GetModelStatusParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WriteToRequest writes these params to a swagger request
func (o *GetModelStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param modelId
	if err := r.SetPathParam("modelId", o.ModelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
