// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// GetModelStatusReader is a Reader for the GetModelStatus structure.
type GetModelStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetModelStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetModelStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetModelStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetModelStatusOK creates a GetModelStatusOK with default headers values
func NewGetModelStatusOK() *GetModelStatusOK {
	return &GetModelStatusOK{}
}

/*
	GetModelStatusOK describes a response with status code 200, with default header values.

OK
*/
type GetModelStatusOK struct {
	Payload *models.GetStatusResponse
}

func (o *GetModelStatusOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status][%d] getModelStatusOK  %+v", 200, o.Payload)
}
func (o *GetModelStatusOK) GetPayload() *models.GetStatusResponse {
	return o.Payload
}

func (o *GetModelStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelStatusUnauthorized creates a GetModelStatusUnauthorized with default headers values
func NewGetModelStatusUnauthorized() *GetModelStatusUnauthorized {
	return &GetModelStatusUnauthorized{}
}

/*
	GetModelStatusUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetModelStatusUnauthorized struct {
	Payload *models.Error
}

func (o *GetModelStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status][%d] getModelStatusUnauthorized  %+v", 401, o.Payload)
}
func (o *GetModelStatusUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelStatusNotFound creates a GetModelStatusNotFound with default headers values
func NewGetModelStatusNotFound() *GetModelStatusNotFound {
	return &GetModelStatusNotFound{}
}

/*
	GetModelStatusNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetModelStatusNotFound struct {
	Payload *models.Error
}

func (o *GetModelStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status][%d] getModelStatusNotFound  %+v", 404, o.Payload)
}
func (o *GetModelStatusNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelStatusInternalServerError creates a GetModelStatusInternalServerError with default headers values
func NewGetModelStatusInternalServerError() *GetModelStatusInternalServerError {
	return &GetModelStatusInternalServerError{}
}

/*
	GetModelStatusInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetModelStatusInternalServerError struct {
	Payload *models.Error
}

func (o *GetModelStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}/status][%d] getModelStatusInternalServerError  %+v", 500, o.Payload)
}
func (o *GetModelStatusInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetModelStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
