// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// PostModelCopyReader is a Reader for the PostModelCopy structure.
type PostModelCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostModelCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostModelCopyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostModelCopyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostModelCopyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostModelCopyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostModelCopyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostModelCopyOK creates a PostModelCopyOK with default headers values
func NewPostModelCopyOK() *PostModelCopyOK {
	return &PostModelCopyOK{}
}

/*
	PostModelCopyOK describes a response with status code 200, with default header values.

OK
*/
type PostModelCopyOK struct {
	Payload *models.PostModelResponse
}

func (o *PostModelCopyOK) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/copy][%d] postModelCopyOK  %+v", 200, o.Payload)
}
func (o *PostModelCopyOK) GetPayload() *models.PostModelResponse {
	return o.Payload
}

func (o *PostModelCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostModelResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelCopyBadRequest creates a PostModelCopyBadRequest with default headers values
func NewPostModelCopyBadRequest() *PostModelCopyBadRequest {
	return &PostModelCopyBadRequest{}
}

/*
	PostModelCopyBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PostModelCopyBadRequest struct {
	Payload *models.Error
}

func (o *PostModelCopyBadRequest) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/copy][%d] postModelCopyBadRequest  %+v", 400, o.Payload)
}
func (o *PostModelCopyBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelCopyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelCopyUnauthorized creates a PostModelCopyUnauthorized with default headers values
func NewPostModelCopyUnauthorized() *PostModelCopyUnauthorized {
	return &PostModelCopyUnauthorized{}
}

/*
	PostModelCopyUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostModelCopyUnauthorized struct {
	Payload *models.Error
}

func (o *PostModelCopyUnauthorized) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/copy][%d] postModelCopyUnauthorized  %+v", 401, o.Payload)
}
func (o *PostModelCopyUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelCopyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelCopyNotFound creates a PostModelCopyNotFound with default headers values
func NewPostModelCopyNotFound() *PostModelCopyNotFound {
	return &PostModelCopyNotFound{}
}

/*
	PostModelCopyNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type PostModelCopyNotFound struct {
	Payload *models.Error
}

func (o *PostModelCopyNotFound) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/copy][%d] postModelCopyNotFound  %+v", 404, o.Payload)
}
func (o *PostModelCopyNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelCopyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelCopyInternalServerError creates a PostModelCopyInternalServerError with default headers values
func NewPostModelCopyInternalServerError() *PostModelCopyInternalServerError {
	return &PostModelCopyInternalServerError{}
}

/*
	PostModelCopyInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostModelCopyInternalServerError struct {
	Payload *models.Error
}

func (o *PostModelCopyInternalServerError) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/copy][%d] postModelCopyInternalServerError  %+v", 500, o.Payload)
}
func (o *PostModelCopyInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelCopyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
