// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// NewPostModelConfigParams creates a new PostModelConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostModelConfigParams() *PostModelConfigParams {
	return &PostModelConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostModelConfigParamsWithTimeout creates a new PostModelConfigParams object
// with the ability to set a timeout on a request.
func NewPostModelConfigParamsWithTimeout(timeout time.Duration) *PostModelConfigParams {
	return &PostModelConfigParams{
		timeout: timeout,
	}
}

// NewPostModelConfigParamsWithContext creates a new PostModelConfigParams object
// with the ability to set a context for a request.
func NewPostModelConfigParamsWithContext(ctx context.Context) *PostModelConfigParams {
	return &PostModelConfigParams{
		Context: ctx,
	}
}

// NewPostModelConfigParamsWithHTTPClient creates a new PostModelConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostModelConfigParamsWithHTTPClient(client *http.Client) *PostModelConfigParams {
	return &PostModelConfigParams{
		HTTPClient: client,
	}
}

/*
PostModelConfigParams contains all the parameters to send to the API endpoint

	for the post model config operation.

	Typically these are written to a http.Request.
*/
type PostModelConfigParams struct {

	// ModelID.
	ModelID string

	/* PostConfigRequest.

	   configuration to apply
	*/
	PostConfigRequest *models.PostConfigRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post model config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostModelConfigParams) WithDefaults() *PostModelConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post model config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostModelConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post model config params
func (o *PostModelConfigParams) WithTimeout(timeout time.Duration) *PostModelConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post model config params
func (o *PostModelConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post model config params
func (o *PostModelConfigParams) WithContext(ctx context.Context) *PostModelConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post model config params
func (o *PostModelConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post model config params
func (o *PostModelConfigParams) WithHTTPClient(client *http.Client) *PostModelConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post model config params
func (o *PostModelConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModelID adds the modelID to the post model config params
func (o *PostModelConfigParams) WithModelID(modelID string) *PostModelConfigParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the post model config params
func (o *PostModelConfigParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WithPostConfigRequest adds the postConfigRequest to the post model config params
func (o *PostModelConfigParams) WithPostConfigRequest(postConfigRequest *models.PostConfigRequest) *PostModelConfigParams {
	o.SetPostConfigRequest(postConfigRequest)
	return o
}

// SetPostConfigRequest adds the postConfigRequest to the post model config params
func (o *PostModelConfigParams) SetPostConfigRequest(postConfigRequest *models.PostConfigRequest) {
	o.PostConfigRequest = postConfigRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostModelConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param modelId
	if err := r.SetPathParam("modelId", o.ModelID); err != nil {
		return err
	}
	if o.PostConfigRequest != nil {
		if err := r.SetBodyParam(o.PostConfigRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
