// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostModelDataSetRunParams creates a new PostModelDataSetRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostModelDataSetRunParams() *PostModelDataSetRunParams {
	return &PostModelDataSetRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostModelDataSetRunParamsWithTimeout creates a new PostModelDataSetRunParams object
// with the ability to set a timeout on a request.
func NewPostModelDataSetRunParamsWithTimeout(timeout time.Duration) *PostModelDataSetRunParams {
	return &PostModelDataSetRunParams{
		timeout: timeout,
	}
}

// NewPostModelDataSetRunParamsWithContext creates a new PostModelDataSetRunParams object
// with the ability to set a context for a request.
func NewPostModelDataSetRunParamsWithContext(ctx context.Context) *PostModelDataSetRunParams {
	return &PostModelDataSetRunParams{
		Context: ctx,
	}
}

// NewPostModelDataSetRunParamsWithHTTPClient creates a new PostModelDataSetRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostModelDataSetRunParamsWithHTTPClient(client *http.Client) *PostModelDataSetRunParams {
	return &PostModelDataSetRunParams{
		HTTPClient: client,
	}
}

/*
PostModelDataSetRunParams contains all the parameters to send to the API endpoint

	for the post model data set run operation.

	Typically these are written to a http.Request.
*/
type PostModelDataSetRunParams struct {

	// ModelID.
	ModelID string

	// Type.
	//
	// Default: "training"
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post model data set run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostModelDataSetRunParams) WithDefaults() *PostModelDataSetRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post model data set run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostModelDataSetRunParams) SetDefaults() {
	var (
		typeVarDefault = string("training")
	)

	val := PostModelDataSetRunParams{
		Type: &typeVarDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the post model data set run params
func (o *PostModelDataSetRunParams) WithTimeout(timeout time.Duration) *PostModelDataSetRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post model data set run params
func (o *PostModelDataSetRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post model data set run params
func (o *PostModelDataSetRunParams) WithContext(ctx context.Context) *PostModelDataSetRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post model data set run params
func (o *PostModelDataSetRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post model data set run params
func (o *PostModelDataSetRunParams) WithHTTPClient(client *http.Client) *PostModelDataSetRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post model data set run params
func (o *PostModelDataSetRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModelID adds the modelID to the post model data set run params
func (o *PostModelDataSetRunParams) WithModelID(modelID string) *PostModelDataSetRunParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the post model data set run params
func (o *PostModelDataSetRunParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WithType adds the typeVar to the post model data set run params
func (o *PostModelDataSetRunParams) WithType(typeVar *string) *PostModelDataSetRunParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the post model data set run params
func (o *PostModelDataSetRunParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *PostModelDataSetRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param modelId
	if err := r.SetPathParam("modelId", o.ModelID); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
