// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// PostModelReader is a Reader for the PostModel structure.
type PostModelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostModelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostModelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostModelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostModelUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostModelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostModelOK creates a PostModelOK with default headers values
func NewPostModelOK() *PostModelOK {
	return &PostModelOK{}
}

/*
	PostModelOK describes a response with status code 200, with default header values.

OK
*/
type PostModelOK struct {
	Payload *models.PostModelResponse
}

func (o *PostModelOK) Error() string {
	return fmt.Sprintf("[POST /models][%d] postModelOK  %+v", 200, o.Payload)
}
func (o *PostModelOK) GetPayload() *models.PostModelResponse {
	return o.Payload
}

func (o *PostModelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostModelResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelBadRequest creates a PostModelBadRequest with default headers values
func NewPostModelBadRequest() *PostModelBadRequest {
	return &PostModelBadRequest{}
}

/*
	PostModelBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PostModelBadRequest struct {
	Payload *models.Error
}

func (o *PostModelBadRequest) Error() string {
	return fmt.Sprintf("[POST /models][%d] postModelBadRequest  %+v", 400, o.Payload)
}
func (o *PostModelBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelUnauthorized creates a PostModelUnauthorized with default headers values
func NewPostModelUnauthorized() *PostModelUnauthorized {
	return &PostModelUnauthorized{}
}

/*
	PostModelUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostModelUnauthorized struct {
	Payload *models.Error
}

func (o *PostModelUnauthorized) Error() string {
	return fmt.Sprintf("[POST /models][%d] postModelUnauthorized  %+v", 401, o.Payload)
}
func (o *PostModelUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelInternalServerError creates a PostModelInternalServerError with default headers values
func NewPostModelInternalServerError() *PostModelInternalServerError {
	return &PostModelInternalServerError{}
}

/*
	PostModelInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostModelInternalServerError struct {
	Payload *models.Error
}

func (o *PostModelInternalServerError) Error() string {
	return fmt.Sprintf("[POST /models][%d] postModelInternalServerError  %+v", 500, o.Payload)
}
func (o *PostModelInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
