// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// NewPostOauth2RefreshParams creates a new PostOauth2RefreshParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOauth2RefreshParams() *PostOauth2RefreshParams {
	return &PostOauth2RefreshParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOauth2RefreshParamsWithTimeout creates a new PostOauth2RefreshParams object
// with the ability to set a timeout on a request.
func NewPostOauth2RefreshParamsWithTimeout(timeout time.Duration) *PostOauth2RefreshParams {
	return &PostOauth2RefreshParams{
		timeout: timeout,
	}
}

// NewPostOauth2RefreshParamsWithContext creates a new PostOauth2RefreshParams object
// with the ability to set a context for a request.
func NewPostOauth2RefreshParamsWithContext(ctx context.Context) *PostOauth2RefreshParams {
	return &PostOauth2RefreshParams{
		Context: ctx,
	}
}

// NewPostOauth2RefreshParamsWithHTTPClient creates a new PostOauth2RefreshParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOauth2RefreshParamsWithHTTPClient(client *http.Client) *PostOauth2RefreshParams {
	return &PostOauth2RefreshParams{
		HTTPClient: client,
	}
}

/*
PostOauth2RefreshParams contains all the parameters to send to the API endpoint

	for the post oauth2 refresh operation.

	Typically these are written to a http.Request.
*/
type PostOauth2RefreshParams struct {

	/* PostOauth2RefreshRequest.

	   Amber account credentials
	*/
	PostOauth2RefreshRequest *models.PostOauth2RefreshRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post oauth2 refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOauth2RefreshParams) WithDefaults() *PostOauth2RefreshParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post oauth2 refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOauth2RefreshParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) WithTimeout(timeout time.Duration) *PostOauth2RefreshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) WithContext(ctx context.Context) *PostOauth2RefreshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) WithHTTPClient(client *http.Client) *PostOauth2RefreshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPostOauth2RefreshRequest adds the postOauth2RefreshRequest to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) WithPostOauth2RefreshRequest(postOauth2RefreshRequest *models.PostOauth2RefreshRequest) *PostOauth2RefreshParams {
	o.SetPostOauth2RefreshRequest(postOauth2RefreshRequest)
	return o
}

// SetPostOauth2RefreshRequest adds the postOauth2RefreshRequest to the post oauth2 refresh params
func (o *PostOauth2RefreshParams) SetPostOauth2RefreshRequest(postOauth2RefreshRequest *models.PostOauth2RefreshRequest) {
	o.PostOauth2RefreshRequest = postOauth2RefreshRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostOauth2RefreshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PostOauth2RefreshRequest != nil {
		if err := r.SetBodyParam(o.PostOauth2RefreshRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
