// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/v2/models"
)

// PostModelOutageReader is a Reader for the PostModelOutage structure.
type PostModelOutageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostModelOutageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostModelOutageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostModelOutageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostModelOutageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostModelOutageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostModelOutageOK creates a PostModelOutageOK with default headers values
func NewPostModelOutageOK() *PostModelOutageOK {
	return &PostModelOutageOK{}
}

/*
	PostModelOutageOK describes a response with status code 200, with default header values.

OK
*/
type PostModelOutageOK struct {
	Payload *models.Error
}

func (o *PostModelOutageOK) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/outage][%d] postModelOutageOK  %+v", 200, o.Payload)
}
func (o *PostModelOutageOK) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelOutageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelOutageUnauthorized creates a PostModelOutageUnauthorized with default headers values
func NewPostModelOutageUnauthorized() *PostModelOutageUnauthorized {
	return &PostModelOutageUnauthorized{}
}

/*
	PostModelOutageUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostModelOutageUnauthorized struct {
	Payload *models.Error
}

func (o *PostModelOutageUnauthorized) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/outage][%d] postModelOutageUnauthorized  %+v", 401, o.Payload)
}
func (o *PostModelOutageUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelOutageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelOutageNotFound creates a PostModelOutageNotFound with default headers values
func NewPostModelOutageNotFound() *PostModelOutageNotFound {
	return &PostModelOutageNotFound{}
}

/*
	PostModelOutageNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type PostModelOutageNotFound struct {
	Payload *models.Error
}

func (o *PostModelOutageNotFound) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/outage][%d] postModelOutageNotFound  %+v", 404, o.Payload)
}
func (o *PostModelOutageNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelOutageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostModelOutageInternalServerError creates a PostModelOutageInternalServerError with default headers values
func NewPostModelOutageInternalServerError() *PostModelOutageInternalServerError {
	return &PostModelOutageInternalServerError{}
}

/*
	PostModelOutageInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostModelOutageInternalServerError struct {
	Payload *models.Error
}

func (o *PostModelOutageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /models/{modelId}/outage][%d] postModelOutageInternalServerError  %+v", 500, o.Payload)
}
func (o *PostModelOutageInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostModelOutageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
