// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOutageParams creates a new PostOutageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOutageParams() *PostOutageParams {
	return &PostOutageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOutageParamsWithTimeout creates a new PostOutageParams object
// with the ability to set a timeout on a request.
func NewPostOutageParamsWithTimeout(timeout time.Duration) *PostOutageParams {
	return &PostOutageParams{
		timeout: timeout,
	}
}

// NewPostOutageParamsWithContext creates a new PostOutageParams object
// with the ability to set a context for a request.
func NewPostOutageParamsWithContext(ctx context.Context) *PostOutageParams {
	return &PostOutageParams{
		Context: ctx,
	}
}

// NewPostOutageParamsWithHTTPClient creates a new PostOutageParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOutageParamsWithHTTPClient(client *http.Client) *PostOutageParams {
	return &PostOutageParams{
		HTTPClient: client,
	}
}

/*
PostOutageParams contains all the parameters to send to the API endpoint

	for the post outage operation.

	Typically these are written to a http.Request.
*/
type PostOutageParams struct {

	/* SensorID.

	   Unique identifier for sensor
	*/
	SensorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post outage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOutageParams) WithDefaults() *PostOutageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post outage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOutageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post outage params
func (o *PostOutageParams) WithTimeout(timeout time.Duration) *PostOutageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post outage params
func (o *PostOutageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post outage params
func (o *PostOutageParams) WithContext(ctx context.Context) *PostOutageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post outage params
func (o *PostOutageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post outage params
func (o *PostOutageParams) WithHTTPClient(client *http.Client) *PostOutageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post outage params
func (o *PostOutageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSensorID adds the sensorID to the post outage params
func (o *PostOutageParams) WithSensorID(sensorID string) *PostOutageParams {
	o.SetSensorID(sensorID)
	return o
}

// SetSensorID adds the sensorId to the post outage params
func (o *PostOutageParams) SetSensorID(sensorID string) {
	o.SensorID = sensorID
}

// WriteToRequest writes these params to a swagger request
func (o *PostOutageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param sensorId
	if err := r.SetHeaderParam("sensorId", o.SensorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
