// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/boonlogic/amber-go-sdk/models"
)

// NewPutSensorParams creates a new PutSensorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSensorParams() *PutSensorParams {
	return &PutSensorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutSensorParamsWithTimeout creates a new PutSensorParams object
// with the ability to set a timeout on a request.
func NewPutSensorParamsWithTimeout(timeout time.Duration) *PutSensorParams {
	return &PutSensorParams{
		timeout: timeout,
	}
}

// NewPutSensorParamsWithContext creates a new PutSensorParams object
// with the ability to set a context for a request.
func NewPutSensorParamsWithContext(ctx context.Context) *PutSensorParams {
	return &PutSensorParams{
		Context: ctx,
	}
}

// NewPutSensorParamsWithHTTPClient creates a new PutSensorParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSensorParamsWithHTTPClient(client *http.Client) *PutSensorParams {
	return &PutSensorParams{
		HTTPClient: client,
	}
}

/*
PutSensorParams contains all the parameters to send to the API endpoint

	for the put sensor operation.

	Typically these are written to a http.Request.
*/
type PutSensorParams struct {

	/* PutSensorRequest.

	   New label to apply to sensor instance
	*/
	PutSensorRequest *models.PutSensorRequest

	/* SensorID.

	   Unique identifier for sensor
	*/
	SensorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put sensor params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSensorParams) WithDefaults() *PutSensorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put sensor params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSensorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put sensor params
func (o *PutSensorParams) WithTimeout(timeout time.Duration) *PutSensorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put sensor params
func (o *PutSensorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put sensor params
func (o *PutSensorParams) WithContext(ctx context.Context) *PutSensorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put sensor params
func (o *PutSensorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put sensor params
func (o *PutSensorParams) WithHTTPClient(client *http.Client) *PutSensorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put sensor params
func (o *PutSensorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPutSensorRequest adds the putSensorRequest to the put sensor params
func (o *PutSensorParams) WithPutSensorRequest(putSensorRequest *models.PutSensorRequest) *PutSensorParams {
	o.SetPutSensorRequest(putSensorRequest)
	return o
}

// SetPutSensorRequest adds the putSensorRequest to the put sensor params
func (o *PutSensorParams) SetPutSensorRequest(putSensorRequest *models.PutSensorRequest) {
	o.PutSensorRequest = putSensorRequest
}

// WithSensorID adds the sensorID to the put sensor params
func (o *PutSensorParams) WithSensorID(sensorID string) *PutSensorParams {
	o.SetSensorID(sensorID)
	return o
}

// SetSensorID adds the sensorId to the put sensor params
func (o *PutSensorParams) SetSensorID(sensorID string) {
	o.SensorID = sensorID
}

// WriteToRequest writes these params to a swagger request
func (o *PutSensorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PutSensorRequest != nil {
		if err := r.SetBodyParam(o.PutSensorRequest); err != nil {
			return err
		}
	}

	// header param sensorId
	if err := r.SetHeaderParam("sensorId", o.SensorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
