// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// MayContainNullsArray may contain nulls array
//
// swagger:model mayContainNullsArray
type MayContainNullsArray []interface{}

// Validate validates this may contain nulls array
func (m MayContainNullsArray) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this may contain nulls array based on context it is used
func (m MayContainNullsArray) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
